sudo: required
dist: trusty

language: minimal

jobs:
  include:
  - name: "deploy dry run"
    env: BUILD=deploy
    script: ./travis/deploy --dry-run

  - stage: deploy
    script: ./travis/deploy
    if: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
