# resolver: lts-17.7
resolver: lts-19.3

packages:
- .
- example-project
nix:
  packages:
    - zlib.dev
    - zlib.out
# Work around https://github.com/commercialhaskell/stack/issues/5290
save-hackage-creds: false
