service: NAME

provider:
  name: aws
  runtime: haskell

functions:
  main:
    handler: shtest.main

  apigw:
    handler: shtest.apigw
    events:
      - http:
          path: hello/{name}
          method: get

  subdir:
    handler: subdir/subtest.main

  jsfunc:
    runtime: nodejs12.x
    handler: jsfunc/handler.main

plugins:
- serverless-haskell
- serverless-offline

custom:
  haskell:
    docker: ${strToBool(${env:FORCE_DOCKER, "DOCKER_DEFAULT"})}
